### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by mattsmith321** [adeshpande3/March-Madness-ML#13]
I'm completely new to pretty much everything in your article but I decided to give it a go. I downloaded Python 3.7.2 for Windows and then followed the instructions on the ReadMe. Started running into issues on the MarchMadness.py step with "ModuleNotFoundError: No module named 'tensorflow'". After some digging, it appears that the stable version of TensorFlow is not compatible with Python 3.7. I did see that I could use the TF nightlies to use Python 3.7 but given my level of experience, that seemed like a rabbit hole I didn't want to go down. So I uninstalled 3.7 and installed 3.6. Then I ran into an issue with the pipfile specifying Python 3.7. I changed that to 3.6 and everything is working out.

Would be great if the ReadMe could be updated to clarify the Python 3 installation requirement to avoid any issues like I did. Of course, that would mean that some other complete newbie like myself who is actually interested in March Madness, machine learning, on Windows, and who didn't already have Python installed...

And yes, I'm sure that I am supposed to update the ReadMe and issue a Pull request myself, but I haven't done anything with git since 2013 and even then it was with a lot of hand holding.

The good news is that I am successfully creating a new training set! Thanks for an informative blog post and creating the project here.

**Comment by adeshpande3** [comment]
Thanks for bringing it up and glad you were able to find a fix! I added a Troubleshooting section in case people have your general setup. One other note is that I forgot to mention that Tensorflow isn't a mandatory requisite for running MarchMadness.py. It's more of an optional library in case you want to create neural network models (Tensorflow/Keras) or if you want to run Gradient Boosted models (Xgboost). Otherwise, having pandas, numpy, and sklearn should be enough. Just wanted to let you know in case you run into additional problems with Tensorflow.
